export {default as Home} from './Home'
export {default as MainLayout} from './MainLayout'
export {default as Tounament} from './Tournament'
export {default as PastedGames} from './pastedGames'
export {default as PlanedGames} from './planedGames'
export {default as Players} from './Players'
export {default as AboutPlayer} from './AboutPlayer'