export {default as Header} from './header'
export {default as Footer} from './footer'
export {default as Banner} from './banner'
export {default as GameCar} from './gameCarusel'
export {default as HomeMedia} from './homeMedia'
export {default as HomePlanedGames} from './homePlanedGames'
export {default as Partners} from './partners'
export {default as TournamentBanner} from './tournamentBanner'